(function(){var g=null;Math.floor(Math.random()*2147483648).toString(36);function i(){var a=Array.prototype.slice.call(arguments),b=a.shift();if(typeof b=="undefined")throw Error("[goog.string.format] Template required");return b.replace(/%([0\-\ \+]*)(\d+)?(\.(\d+))?([%sfdiu])/g,function(b,c,e,f,n,h){if(h=="%")return"%";var q=a.shift();if(typeof q=="undefined")throw Error("[goog.string.format] Not enough arguments");arguments[0]=q;return j[h].apply(g,arguments)})}
var j={s:function(a,b,d){if(isNaN(d)||d==""||a.length>=d)return a;b.indexOf("-",0)>-1?a+=Array(d-a.length+1).join(" "):a=Array(d-a.length+1).join(" ")+a;return a},f:function(a,b,d,c,e){c=a.toString();isNaN(e)||e==""||(c=a.toFixed(e));var f;f=a<0?"-":b.indexOf("+")>=0?"+":b.indexOf(" ")>=0?" ":"";a>=0&&(c=f+c);if(isNaN(d)||c.length>=d)return c;c=isNaN(e)?Math.abs(a).toString():Math.abs(a).toFixed(e);a=d-c.length-f.length;return c=b.indexOf("-",0)>=0?f+c+Array(a+1).join(" "):f+Array(a+1).join(b.indexOf("0",
0)>=0?"0":" ")+c}};j.d=function(a,b,d,c,e,f,n,h){return j.f(parseInt(a,10),b,d,c,0,f,n,h)};j.i=j.d;j.u=j.d;var k=[[0,0]],l={};function m(){var a=Array.prototype.slice.call(arguments),b=a.shift(),d=g;isNaN(parseInt(b))||(d=b,b=a.shift());if($.type(b)==="array"){for(var c=0,e=!1,f=0;f<k.length;f++)if(e=f===k.length-1,d>=k[f][0]&&e||d>=k[f][0]&&d<k[f+1][0])c=k[f][1];b[c]?a.splice(0,0,b[c]):a.splice(0,0,b[0])}else a.splice(0,0,b);if(l[a])return l[a];b=a.length===1?a[0]:i.apply(g,a);return l[a]=b};k=[[0,1],[1,0],[2,1]];function o(a){if(a.Exception)this.p=a.Exception;if(a.Message)this.message=a.Message.replace(/\s+/g," ");if(a.Code)this.code=a.Code;if(a.type)this.type=a.type}o.prototype.toString=function(){var a="";this.type&&(a+="["+this.type+"]");a+=this.p?" "+this.p:" Error";this.code&&(a+=":"+this.code);this.message&&(a+=this.message.length>100?" "+this.message.substr(0,100)+"...":" "+this.message);return a};
function p(a,b){this.url=a;this.error=g;this.j={};this.dataType="text json";this.type="GET";if(b){if(b.spinner)this.a=b.spinner;if(b.dataType)this.dataType=b.dataType;if(b.type)this.type=b.type;b.params&&$.extend(this.j,b.params)}}
p.prototype.query=function(a,b,d,c){var e=this;if(this.g)try{this.g.abort()}catch(f){}if($.type(b)!="string")b=$.extend({},this.j,b);else if(b){var n=$.param(this.j);n&&(b=n+"&"+b)}else b=$.param(this.j);this.a&&this.a.start();this.error=g;var h=$.Deferred();this.g=$.ajax({type:this.type,url:this.url+a,dataType:this.dataType,data:b});this.g.done(function(a,b,c){h.resolve(a,b,c)});this.g.fail(function(a,b,c){var d;try{d=$.parseJSON(a.responseText),d.type=b,c=new o(d)}catch(f){c=new o({type:b,Message:c})}e.error=
c.toString();h.reject(c)});this.g.complete(function(){e.a&&e.a.stop();e.error&&e.a&&e.a.error(e.error.toString())});$.isFunction(d)&&h.done(d);$.isFunction(c)&&h.fail(c);return h.promise()};
function r(a){var b={element:g,classLoading:"kng-ajax-spinner-loading",classError:"kng-ajax-spinner-error",delay:0,timeout:5E3,appendTo:g,inline:a?a.appendTo?!0:!1:!1,modal:!1};$.extend(b,a);this.b=b.element!==g?b.element:$("<div/>").addClass("kng-ajax-spinner").append($("<div/>").addClass("kng-ajax-spinner-icon")).append($("<p/>")).hide();this.appendTo(b.appendTo?b.appendTo:"body");this.h=this.b.children("p:first");this.timeout=b.timeout;this.o=g;this.delay=b.delay;this.k=g;(this.m=b.inline)||this.b.css({"z-index":10001,
position:"fixed"});this.background=g;if(b.modal)this.background=$("<div/>").css({width:$(document).width(),height:$(document).height(),"background-color":"#000",position:"absolute",top:0,left:0,opacity:0.3,"z-index":1E4,display:"none"}).appendTo("body");$(window).bind("resize.spinner",$.proxy(this.n,this))}
r.prototype.n=function(){if(!this.m){var a=$(window).width(),b=$(window).height();this.background&&this.background.css({width:$(document).width(),height:$(document).height()});this.b.css({position:"fixed",left:a/2-this.b.width()/2,top:Math.round(b*0.2)})}};r.prototype.appendTo=function(a){this.b.appendTo(a)};function s(a){a.b.removeClass("kng-ajax-spinner-error").addClass("kng-ajax-spinner-loading");a.h.text(m("working"));a.show()}
r.prototype.start=function(){var a=this;this.o=setTimeout(function(){a.h.text(m("still working..."))},this.timeout);this.delay?this.k=setTimeout(function(){s(a)},this.delay):s(this)};r.prototype.show=function(){this.n();this.b.show();this.m||this.background&&this.background.show()};r.prototype.stop=function(){clearInterval(this.o);clearInterval(this.k);this.k=this.o=g;this.b.removeClass("kng-ajax-spinner-loading").hide();this.background&&this.background.hide();this.h.html("&nbsp;")};
r.prototype.error=function(a){this.stop();this.b.addClass("kng-ajax-spinner-error");this.show();this.h.text(a);this.n()};function t(a){this.form=$(a)}function u(a,b){b!=void 0?($.type(b)=="string"?a.form.find(":input[name="+b+"]:first"):b).closest("li").removeClass("invalid").find("ul.errors").remove():a.form.find(":input").each(function(){$(this).closest("li").removeClass("invalid").find("ul.errors").remove()})};function v(){this.c=$("<div/>");this.a=new r({appendTo:this.c});this.refresh=!1;this.r="";var a=$("#refreshPrompt");if(a.length&&a.val())this.refresh=!0,this.r=a.val();this.a.start();this.c.dialog({modal:!0,buttons:[{text:m("Cancel"),click:$.proxy(this.close,this)},{text:m("Change Location"),click:$.proxy(this.t,this)}]});this.l=$.proxy(function(a){a.which==13&&(a.preventDefault(),this.t())},this);this.v=new p("/location/");this.v.query("load-form",{},$.proxy(this.w,this),$.proxy(this.z,this))}
v.prototype.z=function(){this.a.error("unknown error")};v.prototype.w=function(a){this.a.stop();this.form=$(a.form).appendTo(this.c);$(document).keypress(this.l);this.c.dialog("option","title",this.form.attr("title"));this.q=new t(this.form)};v.prototype.close=function(){this.c.dialog("close");$(document).unbind("keypress",this.l);this.refresh&&arguments.length==1&&arguments[0]===!0&&w(this)};
function w(a){if(!a.e)a.e=$("<div/>").appendTo("body");a.e.html($("<p/>").text(a.r));a.e.dialog({modal:!0,title:m("Refresh page?"),buttons:[{text:m("No"),click:function(){$(this).dialog("destroy")}},{text:m("Refresh"),click:$.proxy(function(){this.e.closest(".ui-dialog").find(".ui-button").button("disable");this.e.empty();this.a.appendTo(this.e);this.a.start();var a=window.location.href,a=a.replace(/where=[^&]*/,"where="+encodeURIComponent($("#where").val())),a=a.replace(/distance=\d*/,"distance="+
encodeURIComponent($("#distance").val()));window.location.href=a},a)}]})}
v.prototype.t=function(){var a=$("#locationModal-where"),b=a.val(),d=this.form.find("#locationModal-radius").val(),c=this.form.find("option:selected").text();if(!b)return u(this.q,a),b=this.q,a=$.type(a)=="string"?b.form.find(":input[name="+a+"]:first"):a,a=a.closest("li"),b=a.find("ul.errors"),a.addClass("invalid"),d=$("<li/>").addClass("blank").text("Please enter a location"),b.length?b.find("li.blank").length||b.append(d):(c=$("<ul/>").addClass("errors"),c.append(d),a.append(c)),b.show(),!1;$("#locationString").text("Within "+
c+" of "+b);$("#where").val(b);$("#distance").val(d);a=new Date;a.setDate(a.getDate()+7);b=d+"--"+b.replace("--","");document.cookie="l="+encodeURIComponent(b)+";expires="+a.toUTCString()+";path=/;domain=.kaango.com";this.close(!0)};v.prototype.open=function(){this.c.dialog("open");$(document).keypress(this.l)};$(function(){var a;$("#change-locationString").click(function(b){b.preventDefault();a?a.open():a=new v})});})()